### ISSUE TITLE
I have a project reference to be embedded in my main project, using its targets, but it only gets embedded in one target.

### ISSUE THREAD

**Issue by Toker42** [RyanBibby/Caesar-Cipher-iPhone-App#3]
I have a project reference to be embedded in my main project, using its targets, but it only gets embedded in one target.

```
projectReferences:
  MyProject:
    path: Projects/MyProject/MyProject.xcodeproj
```

Targets:

```
MyTarget:
  dependencies:
      - target: MyProject/MyProject
        link: true
        embed: true

MyTargetOne:
  dependencies:
      - target: MyProject/MyProject
        link: true
        embed: true
```

Only one of the targets embeds the dependency.

__Originally posted by @sky-duartecosta in https://github.com/yonaskolb/XcodeGen/issues/933__
